name: CI

# Controls when the workflow will run
on:
  # Trigger the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Git (if necessary, macOS usually comes with it)
      - name: Install git
        run: brew install git

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          wget https://github.com/docker/buildx/releases/download/v0.20.1/buildx-v0.20.1.darwin-arm64 -O /usr/local/bin/docker-buildx
          chmod +x /usr/local/bin/docker-buildx
          docker buildx create --use

      # Step 3: Clone the omnibus-gitlab repository from GitLab
      - name: Clone omnibus-gitlab repository
        run: git clone https://gitlab.com/gitlab-org/omnibus-gitlab.git

      # # Step 4: Navigate into the omnibus-gitlab directory
      # - name: Enter omnibus-gitlab directory
      #   run: cd omnibus-gitlab

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: |
          cd omnibus-gitlab
          docker buildx build -t pylab/gitlab .
          docker images
